#!/bin/bash

if test "x$1" = "x" 
then
	echo "Need to provide path to libsimpledsp source"
	exit 1
fi

libSimpleDsp="$1"
shift

doCleanSimpleDsp=""
doRun=""

while test "x$1" != "x"
do
	if test "$1" = "run"
	then
		doRun="yes"
		echo "Runnign speakerman after build"
	elif test "$1" = "clean"
	then
		doCleanSimpleDsp="yes"
		echo "Also clean simpledsp project"
	fi
	shift
done

if test "x$1" = "xrun"
then
	doRun="yes"
else
	doRun=""
fi 

if ! test -f "src/speakerman.cpp"
then
	echo "In wrong directory!"
	exit 1
fi

if ! cd "${libSimpleDsp}"
then
	echo "Couldn't change to ${libSimpleDsp}"
	exit 1
fi

if test -n "$doCleanSimpleDsp"
then
	echo "Cleaning simpledsp project first"
	if ! make clean
	then
		echo "Couldn't clean simpledsp project"
		exit 1
	fi
fi

if ! make -j 
then	
	echo "Couldn't compile libsimpledsp"
	cd - 
	exit 1
fi

echo '>>> Make install: you might need to provide a password here!'

if ! sudo make install
then	
	echo "Couldn't install libsimpledsp"
	exit 1
fi

cd - 

if ! make clean
then
	echo "Couldn't clean speakerman"
	exit 1
fi

if ! make -j
then
	echo "Couldn't build speakerman"
	exit 1
fi

if test "x$doRun" = "xyes"
then
	src/speakerman
fi

