#!/bin/bash

if test "x$1" = "x" 
then
	echo "Need to provide path to libsimpledsp source"
	exit 1
fi

libSimpleDsp="$1"
shift

if test "x$1" = "xrun"
then
	doRun="yes"
else
	doRun=""
fi 

if ! test -f "src/speakerman.cpp"
then
	echo "In wrong directory!"
	exit 1
fi

if ! cd "${libSimpleDsp}"
then
	echo "Couldn't change to ${libSimpleDsp}"
	exit 1
fi

if ! make -j 
then	
	echo "Couldn't compile libsimpledsp"
	cd - 
	exit 1
fi

echo '>>> Make install: you might need to provide a password here!'

if ! sudo make install
then	
	echo "Couldn't install libsimpledsp"
	exit 1
fi

cd - 

if ! make clean
then
	echo "Couldn't clean speakerman"
	exit 1
fi

if ! make -j
then
	echo "Couldn't build speakerman"
	exit 1
fi

if test "x$doRun" = "xyes"
then
	src/speakerman
fi

