#!/bin/bash


# Determine directory of this script
MY_DIR=`dirname "$0"`
pushd "$MY_DIR" >/dev/null
SERVICE_SCRIPT_ROOT=`pwd -P` 
popd >/dev/null

# The directory of the script must indicate the service name
SERVICE_NAME_CANDIDATE=`basename "$SERVICE_SCRIPT_ROOT"`

# Verify if this is indeed a valid service name
if echo "Service $SERVICE_NAME_CANDIDATE" | egrep '^Service [-_0-9a-z]+$' >/dev/null
then
	SERVICE_NAME="$SERVICE_NAME_CANDIDATE"
else
	echo "Need valid service name instead of \"$SERVICE_NAME\"" >&2
	exit 1
fi

export SERVICE_SCRIPT_ROOT
export SERVICE_NAME
export SERVICE_CONFIG_ROOT="/etc/$SERVICE_NAME/"
export SERVICE_HAS_USER="Yes"
export SERVICE_DBUS_INIT="Yes"

# Determine where to log

DEFAULT_LOG_FILE="/var/log/$SERVICE_NAME.log"
LOG_FILE="$DEFAULT_LOG_FILE"
DATE_FORMAT="%Y-%m-%d-%H:%M:%S.%N"
LOG_START_LINE="S: `date +"$DATE_FORMAT"` :: Init system invocation of \"$SERVICE_NAME\" ***"
if ! echo "$LOG_START_LINE" >>"$LOG_FILE"
then
	LOG_FILE="/tmp/$SERVICE_NAME.$$.log"
	echo "$LOG_START_LINE" >>"$LOG_FILE"
fi
echo "Service \"$SERVICE_NAME\" is using log file \"$LOG_FILE\""

# Determine service management script/executable

if [ -n "$SERVICE_HAS_USER" ] 
then
	MANAGER_SCRIPT="manage-service-user"
else
	MANAGER_SCRIPT="manage-service"
fi



MANAGER="$SERVICE_SCRIPT_ROOT/$MANAGER_SCRIPT"

if [ -x "$MANAGER" ]
then
	EXECUTE="$MANAGER $*"
else
	echo "Service management executable not found: \"$MANAGER\"" >&2
	exit 1
fi

echo "Service \"$SERVICE_NAME\" invocation \"$EXECUTE\""

$EXECUTE 2>>"$LOG_FILE" >>"$LOG_FILE"
#$EXECUTE 2>&1 | tee -a "$LOG_FILE"

