#!/bin/bash

SPEAKERMAN_EXECUTABLE_NAME="speakerman"
SERVICE_NAME="Speaker management service"

echo "Executing \"$SERVICE_NAME\" as $USER in home directory \"$HOME\""

SPEAKERMAN_EXECUTABLE_NAME="speakerman"

case "$1" in 
	start)
		ACTION="start"
	;;
	stop)
		ACTION="stop"
	;;
	*)
	echo "Usage (as root): $0 (start|stop)" >&2
	exit 3
esac

# $1 PROGRAM
executable()
{
	# If which is not available then we must be running before
	# /usr is mounted on a system that has which in /usr/bin/.
	# Conclude that $1 is not executable.
	[ -x /bin/which ] || [ -x /usr/bin/which ] || return 1
	which "$1" >/dev/null 2>&1
}

PATH="usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

if executable "$SPEAKERMAN_EXECUTABLE_NAME"
then
	SPEAKERMAN_EXECUTABLE=`which "$SPEAKERMAN_EXECUTABLE_NAME"`
else
	echo "Cannot find $SPEAKERMAN_EXECUTABLE_NAME" >&2
	return 1
fi

# $1: Executable name
# $2: signal
exec_signal() {
	PIDS=`pidof "$1"`
	if [ "$PIDS" == "" ] 
	then
		return 0
	fi
	if ! kill -$2 $PIDS
	then
		echo "Couldn't kill all processes ($1) with kill -$2 $PIDS" >&2
		return 1
	fi
}

# $1: Executable name
exec_await_terminated()
{
	ATTEMPT="0"
	PIDS=`pidof "$1"`
	while [ "$PIDS" != "" ]
	do
		sleep 1
		ATTEMPT=$(($ATTEMPT + 1))
		if [ $ATTEMPT -ge 2 ]
		then	
			return 1
		fi
		PIDS=`pidof "$1"`
	done
}

# $1: Executable name
exec_kill() {
	if ! executable "$1"
	then
		echo "Cannot find $1" >&2
		return 1
	fi
	if ! exec_signal "$1" TERM 
	then
		return 1
	fi
	if exec_await_terminated "$1"
	then
		return 0
	fi
	if ! exec_signal "$1" KILL
	then
		return 1
	fi
	if ! exec_await_terminated "$1"
	then
		return 1
	fi
}

jack_active() {
	if jack_wait -w -t 2 | grep -Ei '^timeout'
	then
		echo "Jack not active"
		return 1
	fi
	return 0;
}

speakerman_activate() {
	if ! exec_kill "$SPEAKERMAN_EXECUTABLE"
	then
		return 1
	fi	
	echo "Executing as $USER: $SPEAKERMAN_EXECUTABLE"

	$SPEAKERMAN_EXECUTABLE &
	disown
	ATTEMPT="0"
	while ! wget --quiet  -O /dev/null "http://localhost:8088"
	do
		sleep 1
		ATTEMPT=$(($ATTEMPT + 1))
		if [ $ATTEMPT -ge 3 ]
		then	
			return 1
		fi
	done
	return 0
}

if [ "$ACTION" == "start" ]
then
	if jack_active && speakerman_activate
	then
		echo "Started"
	fi
else
	if exec_kill "$SPEAKERMAN_EXECUTABLE" 
	then
		echo "Stopped"
	else
		exit 1
	fi
fi
