#!/bin/bash

JACK_EXECUTABLE_SOURCE="/etc/speakerman/jackdrc"
echo Starting JACK audio server...
JACK_EXECUTABLE_SOURCE=

for EXEC_JACK in "$HOME/.jackdrc" "/etc/speakerman/jackdrc"
do
	if [ -r "$EXEC_JACK" ]
	then
		JACK_EXECUTABLE_SOURCE="$EXEC_JACK"
		break
	fi
done

if [ -z "$JACK_EXECUTABLE_SOURCE" ]
then
	echo "Starting jack executable [with default settings]"
	jackd
else
	echo "Starting jack, sourcing \"$JACK_EXECUTABLE_SOURCE\""
	. "$JACK_EXECUTABLE_SOURCE"
fi