#!/bin/bash

JACK_EXECUTABLE_SOURCE="/etc/speakerman/jackdrc"
echo Starting JACK audio server...
JACK_EXECUTABLE_SOURCE=

for EXEC_JACK in "$HOME/.jackdrc" "/etc/speakerman/jackdrc"
do
	if [ -r "$EXEC_JACK" ]
	then
		JACK_EXECUTABLE_SOURCE="$EXEC_JACK"
		break
	fi
done

get_card_name() {
	aplay -l | egrep -m 1 '^card [0-9]+:.*\[USB Audio\]$' | sed -r 's/^[card [0-9]+: ([a-zA-Z0-9]+) .*$/\1/'
}

JACK_CARD=`get_card_name`
echo "Card Name: $JACK_CARD"
export JACK_CARD

if [ -z "$JACK_EXECUTABLE_SOURCE" ]
then
	echo "Starting jack executable [with default settings]"
	jackd
else
	echo "Starting jack, sourcing \"$JACK_EXECUTABLE_SOURCE\""
	. "$JACK_EXECUTABLE_SOURCE"
fi